# Use root/example as user/password credentials
version: '3.1'

services:

  db:
      image: mysql:5.7
      command: ['--character-set-server=utf8', '--collation-server=utf8_general_ci']
      environment:
        - MYSQL_ROOT_PASSWORD=rootpass
        - MYSQL_DATABASE=test_db
        - MYSQL_USER=admin
        - MYSQL_PASSWORD=dbpass
        - MYSQL_HOST=%
      ports:
        - "3309:3306"
      volumes:
        - db:/var/lib/mysql
volumes:
  db: